-- RLS for content platform runtime tables (049).

ALTER TABLE world_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE world_segment_refs ENABLE ROW LEVEL SECURITY;
ALTER TABLE world_truth_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE world_role_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_role_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_vote_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_vote_ballots ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_private_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE world_quality_reports ENABLE ROW LEVEL SECURITY;
