export const state = {
  view: "landing",
  user: null,
  authStatus: "checking",
  authError: "",
  authMode: "login",
  authConfig: null,
  pendingVerificationEmail: "",
  pendingVerificationChallenge: null,
  canResendVerification: false,
  busy: false,
  toast: "",
  error: "",
  apiError: "",
  loading: false,

  worlds: [],
  rooms: [],
  room: null,
  runtimeContent: null,
  currentState: null,
  studio: null,
  cloudWorldSegments: [],
  rules: [],
  cloudWorldLogs: [],

  cloudHostPlayers: [],
  cloudHostPlayersError: "",
  cloudHostStuckCount: 0,
  cloudHostEvents: [],
  cloudHostClueMatrix: null,
  cloudHostAuditLog: [],
  cloudHostTestimonies: [],
  cloudHostSegmentRemedies: [],
  cloudHostVotes: [],
  cloudHostPrivateActions: [],
  cloudHostMiniGames: [],
  cloudRunReport: null,
  cloudRulesPreview: null,
  hostEventSelection: [],
  hostEventWorkspace: null,
  hostVoteWorkspace: null,
  hostRoomCreateWorkspace: null,
  hostSelectedActKey: "",
  hostOperation: null,
  hostArchiveWorkspace: null,
  hostRuleWorkspace: null,
  hostRuleListBusy: "",
  hostRuleListMessage: "",
  hostRuleDeleteConfirmId: "",
  hostRuleAudit: null,
  panelCollapse: {},

  roomEventsConnected: false,
  roomEventsStatus: "idle",

  /** 节奏计时器状态 — 保存在 localStorage，仅主持人本地使用，不同步给玩家 */
  paceTimer: null
};
