/**
 * Canonical API error codes → HTTP status + default message.
 * All route handlers should use throwErr / sendErr from api-errors.js.
 */
export const API_ERRORS = {
  // Auth & session
  AUTH_REQUIRED: { status: 401, message: "Authentication required" },
  INVALID_CREDENTIALS: { status: 401, message: "Email or password is incorrect" },
  EMAIL_INVALID: { status: 400, message: "Valid email is required" },
  DISPLAY_NAME_INVALID: { status: 400, message: "Display name must contain between 2 and 40 characters" },
  EMAIL_ALREADY_REGISTERED: { status: 409, message: "Email is already registered" },
  EMAIL_VERIFICATION_PENDING: { status: 409, message: "Account exists but email verification is pending" },
  USER_NOT_FOUND: { status: 404, message: "User not found" },
  EMAIL_NOT_CONFIGURED: { status: 503, message: "Email is not configured on the server" },
  EMAIL_NOT_VERIFIED: { status: 403, message: "Email address is not verified" },
  STRIPE_NOT_CONFIGURED: { status: 503, message: "Stripe billing is not configured on the server" },
  STRIPE_WEBHOOK_INVALID: { status: 400, message: "Invalid Stripe webhook signature or payload" },
  STRIPE_PLAN_UNAVAILABLE: { status: 400, message: "Selected plan is not available for checkout" },
  STRIPE_API_ERROR: { status: 502, message: "Stripe API request failed" },
  PASSWORD_RESET_INVALID: { status: 400, message: "Password reset link is invalid or expired" },
  EMAIL_VERIFICATION_INVALID: { status: 400, message: "Email verification link is invalid or expired" },
  AUTH_RECOVERY_WRITE_BUSY: { status: 409, message: "Authentication recovery is busy; retry shortly" },
  AUTH_RECOVERY_WRITE_TIMEOUT: { status: 503, message: "Authentication recovery exceeded its safe execution window" },
  AUTH_RECOVERY_TOKEN_UNAVAILABLE: { status: 503, message: "Authentication recovery token could not be allocated" },
  IDENTITY_WRITE_BUSY: { status: 409, message: "Identity write is busy; retry shortly" },
  IDENTITY_WRITE_TIMEOUT: { status: 503, message: "Identity write exceeded its safe execution window" },
  GUEST_ACCOUNT_RESTRICTED: { status: 403, message: "Guest accounts cannot perform this action. Please register to continue." },
  ACCOUNT_ALREADY_REGISTERED: { status: 409, message: "Account is already registered" },
  GUEST_CREATE_RATE_LIMITED: { status: 429, message: "Guest account creation rate limit exceeded" },
  REGISTER_IP_RATE_LIMITED: { status: 429, message: "Registration rate limit exceeded for this network" },
  PLAY_SOCIAL_ACCOUNT_TOO_NEW: { status: 403, message: "Account too new for social features" },
  ACCOUNT_DELETE_BLOCKED: { status: 403, message: "Account cannot be deleted in the current state" },
  ACCOUNT_DELETE_CONFIRMATION_INVALID: { status: 400, message: "Confirmation text does not match your display name" },
  WORLD_VERSION_CONFLICT: { status: 409, message: "World content was modified by another session" },
  WORLD_REVISION_REQUIRED: { status: 428, message: "If-Match world revision is required" },
  SESSION_NOT_FOUND: { status: 404, message: "Session not found" },
  WORLD_INVITE_INVALID: { status: 400, message: "Collaboration invite is invalid or expired" },
  WORLD_INVITE_EMAIL_MISMATCH: { status: 403, message: "Invite email does not match your account" },
  WORLD_INVITE_NOT_FOUND: { status: 404, message: "Pending collaboration invite not found" },
  WORLD_INVITE_SELF: { status: 400, message: "You cannot invite your own email address" },
  OAUTH_PROVIDER_DISABLED: { status: 503, message: "OAuth provider is not configured" },
  OAUTH_STATE_INVALID: { status: 400, message: "OAuth state is invalid or expired" },
  OAUTH_EXCHANGE_FAILED: { status: 502, message: "OAuth authorization failed" },
  OAUTH_EMAIL_REQUIRED: { status: 422, message: "OAuth provider did not return an email address" },
  OAUTH_EMAIL_UNVERIFIED: { status: 422, message: "OAuth provider did not return a verified email address" },
  OAUTH_IDENTITY_CONFLICT: { status: 409, message: "OAuth identity could not be linked safely" },
  OAUTH_LOGIN_CODE_INVALID: { status: 400, message: "OAuth login code is invalid or expired" },

  // Access control
  FORBIDDEN: { status: 403, message: "无权执行此操作" },
  ROOM_MEMBERSHIP_REQUIRED: { status: 403, message: "需要加入该运行房后才能继续" },
  WORLD_EDITOR_REQUIRED: { status: 403, message: "需要剧本编辑权限（拥有者或编辑者）" },
  WORLD_ACCESS_DENIED: { status: 403, message: "无权访问该剧本" },
  HOST_ROLE_REQUIRED: { status: 403, message: "需要主持人权限" },
  VOICE_ACCESS_DENIED: { status: 403, message: "无权进入该语音房" },

  // Generic request
  BAD_REQUEST: { status: 400, message: "Bad request" },
  VALIDATION_ERROR: { status: 400, message: "Validation failed" },
  NOT_FOUND: { status: 404, message: "Not found" },
  CONFLICT: { status: 409, message: "Conflict" },
  IDEMPOTENCY_CONFLICT: { status: 409, message: "Idempotency key conflict" },
  IDEMPOTENCY_ROUTE_MISMATCH: { status: 409, message: "Idempotency key was already used for another route" },
  IDEMPOTENCY_PAYLOAD_MISMATCH: { status: 409, message: "Idempotency key was already used with another request body" },
  IDEMPOTENCY_IN_PROGRESS: { status: 409, message: "Idempotent request is still processing" },
  IDEMPOTENCY_PREVIOUS_FAILED: { status: 409, message: "Previous idempotent request failed" },
  IDEMPOTENCY_KEY_REQUIRED: { status: 400, message: "Idempotency-Key header is required" },
  PAYLOAD_TOO_LARGE: { status: 413, message: "Payload too large" },
  UNSUPPORTED_MEDIA_TYPE: { status: 415, message: "Unsupported media type" },
  UNPROCESSABLE: { status: 422, message: "Unprocessable entity" },
  RATE_LIMITED: { status: 429, message: "Too many requests" },
  PLAZA_POST_INVALID: { status: 400, message: "Plaza post body invalid" },
  PLAZA_POST_NOT_FOUND: { status: 404, message: "Plaza post not found" },
  PLAZA_REPLY_INVALID: { status: 400, message: "Plaza reply body invalid" },
  PLAZA_REPLY_REJECTED: { status: 422, message: "Plaza reply rejected by review" },
  PLAZA_REPLY_NOT_FOUND: { status: 404, message: "Plaza reply not found" },
  PLAZA_REPORT_INVALID: { status: 400, message: "Plaza report reason invalid" },
  PLAZA_REPORT_SELF: { status: 400, message: "Cannot report own content" },
  PLAZA_POST_REJECTED: { status: 422, message: "Plaza post rejected by review" },
  PLAZA_OPS_NOTE_REQUIRED: { status: 400, message: "Ops review note required" },
  PLAZA_REPORT_NOT_FOUND: { status: 404, message: "Plaza report not found" },
  FRIEND_SELF: { status: 400, message: "Cannot add yourself as friend" },
  FRIEND_ALREADY: { status: 409, message: "Already friends" },
  FRIEND_REQUEST_EXISTS: { status: 409, message: "Friend request already exists" },
  FRIEND_REQUEST_NOT_FOUND: { status: 404, message: "Friend request not found" },
  DM_FRIEND_REQUIRED: { status: 403, message: "Direct messages require friendship" },
  DM_NOT_FOUND: { status: 404, message: "Conversation not found" },
  DM_MESSAGE_INVALID: { status: 400, message: "Direct message body invalid" },
  PLAY_CONTENT_FORBIDDEN: { status: 422, message: "Content contains prohibited terms" },
  PLAY_CONTENT_AD: { status: 422, message: "Advertising is not allowed in plaza or direct messages" },
  INTERNAL_ERROR: { status: 500, message: "Internal error" },
  UPSTREAM_ERROR: { status: 502, message: "Upstream service error" },
  /** DeepSeek chat/completions HTTP or quota failure */
  DEEPSEEK_API_ERROR: { status: 502, message: "DeepSeek API request failed" },
  /** 织幕积分不足，无法继续 AI 辅助 */
  CREDITS_EXHAUSTED: { status: 402, message: "织幕积分不足，请等待月度赠送或联系 support 扩容" },
  /** Empty body, truncated JSON, or other unparseable model output */
  DEEPSEEK_RESPONSE_INVALID: { status: 502, message: "DeepSeek API returned invalid response" },
  /** Model reached the configured output-token budget before completing JSON */
  DEEPSEEK_RESPONSE_TRUNCATED: { status: 502, message: "DeepSeek API output reached the token limit" },
  /** Model output parsed but failed schema / length / consistency checks */
  DEEPSEEK_OUTPUT_INVALID: { status: 422, message: "DeepSeek output failed validation" },
  UNAVAILABLE: { status: 503, message: "Service unavailable" },
  IDEMPOTENCY_UNAVAILABLE: { status: 503, message: "Idempotency service is unavailable" },
  GATEWAY_TIMEOUT: { status: 504, message: "Gateway timeout" },

  // Worlds & collaboration
  WORLD_NOT_FOUND: { status: 404, message: "World not found" },
  WORLD_QUOTA_EXCEEDED: { status: 403, message: "World quota exceeded" },
  WORLD_OWNER_REQUIRED: { status: 403, message: "仅剧本拥有者可执行此操作" },
  CATALOG_NOT_PUBLIC: { status: 403, message: "This world is not listed in the public catalog" },
  CATALOG_SELF_PUBLISH_DISABLED: { status: 403, message: "Public catalog listing requires manual review. Submit a review request instead." },
  CATALOG_REVIEW_PENDING: { status: 409, message: "A catalog review request is already pending for this world" },
  CATALOG_ALREADY_PUBLIC: { status: 409, message: "This world is already listed in the public catalog" },
  CATALOG_REVIEW_AGREEMENT_REQUIRED: { status: 400, message: "You must confirm the content policy agreement" },
  CATALOG_REVIEW_NOTES_TOO_SHORT: { status: 400, message: "请填写更详细的审核说明" },
  CATALOG_REVIEW_NOT_PENDING: { status: 409, message: "该剧本当前不在审核中" },
  CATALOG_REVIEW_REJECT_NOTE_REQUIRED: { status: 400, message: "拒审说明至少 4 个字" },
  CATALOG_READINESS_BLOCKED: { status: 400, message: "剧本尚未满足公开库上架要求" },
  WIZARD_BOOTSTRAP_INVALID: { status: 400, message: "向导创建参数无效" },
  WORLD_TEMPLATE_NOT_FOUND: { status: 404, message: "未找到该剧本模板" },
  BETA_APPLICATIONS_CLOSED: { status: 503, message: "内测申请暂未开放" },
  BETA_APPLICATION_PENDING: { status: 409, message: "该邮箱已有待审的内测申请" },
  BETA_APPLICATION_NOT_FOUND: { status: 404, message: "未找到该内测申请" },
  BETA_APPLICATION_NOT_PENDING: { status: 409, message: "该申请当前不在待审状态" },
  BETA_APPLICATION_INVALID: { status: 400, message: "内测申请参数无效" },
  BETA_APPLICATION_NOTES_TOO_SHORT: { status: 400, message: "请填写更详细的使用说明" },
  BETA_APPLICATION_REJECT_NOTE_REQUIRED: { status: 400, message: "拒审说明至少 4 个字" },
  PLAN_UPGRADE_INVALID: { status: 400, message: "升级档位无效" },
  PLAN_UPGRADE_ALREADY_ON_PLAN: { status: 409, message: "当前套餐已满足或高于所选档位" },
  PLAN_UPGRADE_REQUEST_PENDING: { status: 409, message: "你已有待处理的升级申请" },
  PLAN_UPGRADE_NOTES_TOO_SHORT: { status: 400, message: "请填写更详细的申请说明" },
  WORLD_DELETE_BLOCKED: { status: 409, message: "Cannot delete world while dependent runtime data still exists" },
  COLLABORATOR_NOT_REGISTERED: { status: 404, message: "该邮箱尚未注册，请先让协作者完成注册。" },
  COLLABORATOR_ALREADY_MEMBER: { status: 409, message: "This email is already a collaborator on this world" },
  COLLABORATION_MEMBER_NOT_FOUND: { status: 404, message: "Collaboration member not found or owner cannot be changed" },
  COLLABORATION_ROLE_INVALID: { status: 400, message: "Unsupported collaboration role" },

  // Rooms & players
  ROOM_NOT_FOUND: { status: 404, message: "Room not found" },
  ROOM_LISTING_FORBIDDEN: { status: 403, message: "Only this room's host or a world editor may change its public listing" },
  ROOM_INVITE_CODE_UNAVAILABLE: { status: 503, message: "Could not allocate a unique room invite code; retry shortly" },
  CREATOR_ROOM_WRITE_BUSY: { status: 409, message: "Creator room write is busy; retry shortly" },
  CREATOR_ROOM_WRITE_TIMEOUT: { status: 503, message: "Creator room write exceeded its safe execution window" },
  ROOM_RELEASE_REQUIRED: { status: 409, message: "请先创建发布版本，再开放默认冻结的运行房" },
  ROOM_PUBLIC_LISTING_REQUIRES_RELEASE: { status: 409, message: "公开运行房必须绑定不可变发布版本" },
  ROOM_RELEASE_CHANGE_FORBIDDEN: { status: 403, message: "仅房间主持人、协同主持人或世界编辑可变更运行版本" },
  ROOM_RELEASE_ALREADY_BOUND: { status: 409, message: "房间已经绑定该发布版本" },
  ROOM_RELEASE_CHANGE_AFTER_START: { status: 409, message: "房间已产生运行数据，不能原地切换发布版本" },
  ROOM_RELEASE_IMPACT_BLOCKED: { status: 409, message: "目标版本与当前房间状态不兼容" },
  ROOM_RELEASE_IMPACT_STALE: { status: 409, message: "房间状态已变化，请重新生成版本影响预览" },
  ROOM_RELEASE_BINDING_CONFLICT: { status: 409, message: "房间当前版本与确认时不一致，请刷新后重试" },
  ROOM_RELEASE_DIGEST_MISMATCH: { status: 409, message: "目标发布版本校验值不一致，请重新选择版本" },
  PLAYER_ROLE_REQUIRED: { status: 409, message: "Player role required" },
  ROLE_SLOT_OCCUPIED: { status: 409, message: "Role slot already occupied" },
  ROLE_SLOT_NOT_OCCUPIED: { status: 409, message: "No active player on this role seat" },
  ROLE_ALREADY_BOUND: { status: 409, message: "Player already bound to another role in this room" },
  ROLE_SLOT_NOT_FOUND: { status: 404, message: "Role slot not found" },
  ROLE_SEQUENCE_CONFLICT: { status: 409, message: "Another role already uses this sequence" },
  LAST_ROLE_SLOT_REQUIRED: { status: 409, message: "A world must keep at least one role slot" },
  ROLE_SLOT_IN_USE: { status: 409, message: "Role slot is assigned to an active room member" },
  ROLE_SLOT_WORLD_MISMATCH: { status: 400, message: "Role slot not found in room world" },
  ROLE_RELATIONSHIP_SELF_INVALID: { status: 400, message: "A role relationship requires two different roles" },
  SEGMENT_WORLD_MISMATCH: { status: 400, message: "Segment not found in room world" },
  SEGMENT_REFERENCE_WORLD_MISMATCH: { status: 400, message: "Segment reference does not belong to this world" },
  SEGMENT_REFERENCES_INVALID: { status: 400, message: "Segment references are invalid" },
  PRIVATE_ACTION_TARGET_REQUIRED: { status: 400, message: "Target role is required for target-visible private actions" },
  PRIVATE_ACTION_TRANSITION_INVALID: { status: 409, message: "Private action status transition is invalid" },
  INVITE_FIELDS_REQUIRED: { status: 400, message: "inviteCode and roleSlotId are required" },

  // Creator content
  NAME_REQUIRED: { status: 400, message: "name is required" },
  NAME_EMPTY: { status: 400, message: "name cannot be empty" },
  TITLE_REQUIRED: { status: 400, message: "title is required" },
  TITLE_EMPTY: { status: 400, message: "title cannot be empty" },
  TITLE_BODY_SEQUENCE_REQUIRED: { status: 400, message: "title, body and sequence are required" },
  TITLE_BODY_REQUIRED: { status: 400, message: "title and body are required" },
  SEQUENCE_REQUIRED: { status: 400, message: "name and sequence are required" },
  ROOM_NAME_INVITE_REQUIRED: { status: 400, message: "name and inviteCode are required" },
  PUBLICATION_STATUS_INVALID: { status: 400, message: "Unsupported publicationStatus" },
  CHAPTER_NOT_FOUND: { status: 404, message: "Chapter not found" },
  CHAPTER_SEQUENCE_CONFLICT: { status: 409, message: "Another chapter already uses this sequence" },
  SCRIPT_SECTION_NOT_FOUND: { status: 404, message: "Script section not found" },
  SECTION_NOT_FOUND: { status: 404, message: "Script section not found for role" },
  SECTION_LOCKED: { status: 404, message: "Script section is locked or unavailable" },
  SECTION_ALWAYS_AVAILABLE: { status: 409, message: "The first script section cannot be relocked" },
  CONTENT_VERSION_NOT_FOUND: { status: 404, message: "Content version not found" },
  CONTENT_VERSION_INVALID: { status: 422, message: "Content version snapshot is invalid" },
  CONTENT_VERSION_TOO_LARGE: { status: 413, message: "Content version snapshot exceeds the safe restore limit" },
  CONTENT_VERSION_LIMIT_REACHED: { status: 409, message: "Content version limit reached for this world" },
  WORLD_RELEASE_READINESS_BLOCKED: { status: 422, message: "发布版本仍有阻塞问题，请先完成发布检查" },
  WORLD_RELEASE_SNAPSHOT_INVALID: { status: 422, message: "发布版本快照不完整或格式无效" },
  WORLD_RELEASE_TOO_LARGE: { status: 413, message: "发布版本超过安全大小限制" },
  WORLD_RELEASE_LIMIT_REACHED: { status: 409, message: "该剧本的发布版本数量已达到上限" },
  WORLD_RELEASE_WRITE_BUSY: { status: 409, message: "正在生成其他发布版本，请稍后重试" },
  WORLD_RELEASE_WRITE_TIMEOUT: { status: 503, message: "发布版本生成超过安全执行时间" },
  WORLD_RELEASE_NOT_FOUND: { status: 404, message: "未找到当前剧本的发布版本" },
  RELEASE_BOUND_CONTENT_IN_USE: { status: 409, message: "该内容仍被冻结运行房使用；请先结束或迁移相关房间" },
  CREATOR_REVIEW_ACCESS_DENIED: { status: 403, message: "Editorial review access is not available for this membership" },
  CREATOR_REVIEW_NOT_FOUND: { status: 404, message: "Creator review entry not found" },
  CREATOR_REVIEW_TARGET_INVALID: { status: 400, message: "Review target does not belong to this world" },
  CREATOR_REVIEW_EDIT_FORBIDDEN: { status: 403, message: "Only the author or a world editor may edit this review" },
  CREATOR_REVIEW_RESOLVE_FORBIDDEN: { status: 403, message: "Only a world editor may resolve or dismiss a review" },
  CREATOR_REVIEW_PAYLOAD_INVALID: { status: 400, message: "Review anchor and suggestion must be JSON objects" },
  CREATOR_REVIEW_PAYLOAD_TOO_LARGE: { status: 413, message: "Review anchor or structured suggestion exceeds the safe limit" },
  SECTION_SEQUENCE_CONFLICT: { status: 409, message: "Another section already uses this sequence" },
  CREATOR_STRUCTURE_WRITE_BUSY: { status: 409, message: "Creator structure write is busy; retry shortly" },
  CREATOR_STRUCTURE_WRITE_TIMEOUT: { status: 503, message: "Creator structure write exceeded its safe execution window" },
  PARSED_DOCUMENT_REQUIRED: { status: 400, message: "Parsed document is required" },
  ROLE_SLOT_IMPORT_REQUIRED: { status: 400, message: "Valid roleSlotId is required for role script import" },
  NOTEBOOK_FIELDS_REQUIRED: { status: 400, message: "sourceType, title and body are required" },
  NOTEBOOK_SOURCE_INVALID: { status: 404, message: "Notebook source is unavailable for this player" },
  NOTEBOOK_ENTRY_NOT_FOUND: { status: 404, message: "Notebook entry not found" },

  // Studio & graph
  SCENE_NOT_FOUND: { status: 404, message: "Scene not found" },
  SCENE_WORLD_MISMATCH: { status: 404, message: "Scene not found in world" },
  CLUE_NOT_FOUND: { status: 404, message: "Clue not found" },
  CLUE_WORLD_MISMATCH: { status: 404, message: "Clue not found in room world" },
  CLUE_NOT_OWNED: { status: 404, message: "Clue not owned" },
  CLUE_NOT_ACCESSIBLE: { status: 404, message: "Clue not accessible" },
  CLUE_OWNERSHIP_NOT_FOUND: { status: 404, message: "Clue ownership not found" },
  TRUTH_CLAIM_EMPTY: { status: 400, message: "Truth claim cannot be empty" },
  TRUTH_CLAIM_NOT_FOUND: { status: 404, message: "Truth claim not found" },
  TRUTH_CLAIM_KEY_CONFLICT: { status: 409, message: "Truth claim key already exists in this world" },
  TRUTH_CLAIM_REFERENCED: { status: 409, message: "Truth claim is referenced by content segments" },
  CONTENT_PLATFORM_WRITE_BUSY: { status: 409, message: "Content platform write is busy; retry shortly" },
  CONTENT_PLATFORM_WRITE_TIMEOUT: { status: 503, message: "Content platform write exceeded its safe execution window" },
  VISIBILITY_INVALID: { status: 400, message: "Unsupported visibility" },
  ITEM_NOT_FOUND: { status: 404, message: "Item not found" },
  ITEM_REFERENCED: { status: 409, message: "Item is referenced by investigation points" },
  INVESTIGATION_POINT_NOT_FOUND: { status: 404, message: "Investigation point not found" },
  INVESTIGATION_POINT_UNAVAILABLE: { status: 404, message: "Investigation point is locked or unavailable" },
  REQUIRED_ITEM_MISSING: { status: 409, message: "Required item is missing" },
  STORY_EDGE_NOT_FOUND: { status: 404, message: "Story edge not found" },
  STUDIO_NODE_NOT_FOUND: { status: 404, message: "Studio node not found" },
  NODE_TYPE_UNSUPPORTED: { status: 400, message: "Unsupported nodeType" },
  NODE_TYPE_DRAG_UNSUPPORTED: { status: 400, message: "Unsupported draggable nodeType" },
  STUDIO_WRITE_BUSY: { status: 409, message: "Studio content is busy; retry shortly" },
  STUDIO_WRITE_TIMEOUT: { status: 503, message: "Studio content write exceeded its safe execution window" },
  STORY_EDGE_FIELDS_REQUIRED: { status: 400, message: "Valid fromType, fromId, toType and toId are required" },
  RELATION_TYPE_INVALID: { status: 400, message: "Unsupported relationType" },
  POSITION_FIELDS_REQUIRED: { status: 400, message: "Finite x and y are required" },
  ANCHORS_INVALID: { status: 400, message: "anchors must contain between 1 and 8 connection points" },
  ANCHOR_FIELDS_INVALID: { status: 400, message: "Each anchor requires id, x and y" },
  POSITIONS_INVALID: { status: 400, message: "positions must be an array of up to 300 nodes" },
  POSITION_ENTRY_INVALID: { status: 400, message: "Each position requires a valid type, id, x and y" },
  STUDIO_LAYOUT_MODE_INVALID: { status: 400, message: "Unknown story layout mode" },
  PHYSICAL_TOKEN_NOT_FOUND: { status: 404, message: "Physical token not found" },
  PHYSICAL_TOKEN_CODE_INVALID: { status: 400, message: "Physical token code format is invalid" },
  PHYSICAL_TOKEN_CODE_TAKEN: { status: 409, message: "Physical token code is already in use" },
  PHYSICAL_TOKEN_CONTENT_TYPE_INVALID: { status: 400, message: "Unsupported physical token content type" },
  PHYSICAL_TOKEN_CONTENT_NOT_FOUND: { status: 404, message: "Linked content not found in this world" },
  PHYSICAL_TOKEN_METADATA_INVALID: { status: 400, message: "Physical token metadata is invalid" },
  PHYSICAL_TOKEN_REVOKE_INVALID: { status: 409, message: "Only issued tokens can be revoked" },
  PHYSICAL_TOKEN_ALREADY_ACTIVATED: { status: 409, message: "Physical token has already been activated" },
  PHYSICAL_TOKEN_REVOKED: { status: 409, message: "Physical token has been revoked" },
  PHYSICAL_TOKEN_EXPIRED: { status: 410, message: "Physical token has expired" },
  PHYSICAL_TOKEN_WORLD_MISMATCH: { status: 409, message: "Physical token does not belong to this room's world" },
  PHYSICAL_TOKEN_ROLE_FORBIDDEN: { status: 403, message: "Your role cannot activate this physical token" },
  PHYSICAL_TOKEN_PLAYER_ROLE_REQUIRED: { status: 403, message: "Activate physical tokens from a player seat with a role" },
  TUMP_PROOF_REQUIRED: { status: 402, message: "tump transaction proof is required to activate this token" },
  TUMP_PROOF_INSUFFICIENT: { status: 402, message: "tump transaction amount is insufficient" },
  TUMP_INTEGRATION_DISABLED: { status: 503, message: "tump activation is disabled until ledger verification is configured" },

  // Rules
  RULE_NOT_FOUND: { status: 404, message: "Rule not found" },
  RULE_FIELDS_REQUIRED: { status: 400, message: "name, conditions and actions are required" },
  RULE_MODE_INVALID: { status: 400, message: "Unsupported rule mode" },
  RULE_ROOM_WORLD_MISMATCH: { status: 400, message: "roomId does not belong to worldId" },
  RULE_NOT_MANUAL: { status: 400, message: "Only manual rules can be triggered explicitly" },
  RULE_DISABLED: { status: 409, message: "Rule is disabled" },
  RULE_ROOM_SCOPE_MISMATCH: { status: 400, message: "Rule is not bound to this room" },
  RULE_CONDITIONS_NOT_MET: { status: 409, message: "Rule conditions are not satisfied" },
  RULE_BODY_INVALID: { status: 422, message: "Rule conditions or actions failed validation" },

  // Runtime / host
  HOST_EVENT_NOT_FOUND: { status: 404, message: "Pending host event not found" },
  HOST_EVENT_ALREADY_RESOLVED: { status: 409, message: "Host event already resolved" },
  CHECKPOINT_NOT_FOUND: { status: 404, message: "Checkpoint not found" },
  CHECKPOINT_WORLD_MISMATCH: { status: 400, message: "Checkpoint and target room must belong to the same world" },
  CHECKPOINT_RESTORE_BUSY: { status: 409, message: "Another checkpoint restore is in progress" },
  CHECKPOINT_RESTORE_TIMEOUT: { status: 503, message: "Checkpoint restore timed out safely" },
  INVALID_SNAPSHOT: { status: 422, message: "Checkpoint snapshot is invalid or incomplete" },
  SNAPSHOT_VERSION_UNSUPPORTED: { status: 422, message: "Checkpoint snapshot version is too old to restore" },
  SNAPSHOT_TIMELINE_TRUNCATED: { status: 422, message: "Checkpoint timeline is truncated and cannot safely replace the full timeline" },
  RECAP_NOT_FOUND: { status: 404, message: "Recap not found" },
  RECAP_NOT_GENERATED: { status: 404, message: "No recap generated yet" },
  RECAP_TITLE_REQUIRED: { status: 400, message: "Recap title is required" },
  RECAP_GENERATION_IN_PROGRESS: { status: 409, message: "Another recap is being generated for this room" },
  RECAP_GENERATION_TIMEOUT: { status: 503, message: "Recap generation timed out safely" },
  RECAP_LIMIT_REACHED: { status: 409, message: "This room has reached the recap retention limit" },
  RECAP_TOO_LARGE: { status: 413, message: "Recap snapshot exceeds the safe size limit" },
  NO_PLAYERS_TO_NUDGE: { status: 400, message: "No joined players to notify" },
  HOST_COMMUNICATION_BUSY: { status: 409, message: "Host communication is busy" },
  HOST_COMMUNICATION_TIMEOUT: { status: 503, message: "Host communication timed out safely" },
  HOST_PLAYER_MANAGEMENT_BUSY: { status: 409, message: "Host player management is busy" },
  HOST_PLAYER_MANAGEMENT_TIMEOUT: { status: 503, message: "Host player management timed out safely" },
  HOST_GAME_CONTROL_BUSY: { status: 409, message: "Host game control is busy; retry shortly" },
  HOST_GAME_CONTROL_TIMEOUT: { status: 503, message: "Host game control timed out safely" },

  // Voice & LiveKit
  VOICE_ROOM_NAME_REQUIRED: { status: 400, message: "Voice room name is required" },
  VOICE_ROOM_TYPE_INVALID: { status: 400, message: "Unsupported voice room type" },
  VOICE_INVITE_LIST_INVALID: { status: 400, message: "inviteUserIds must be an array of up to 20 members" },
  VOICE_INVITE_COUNT_INVALID: { status: 400, message: "inviteUserIds must contain between 1 and 20 members" },
  VOICE_PUBLIC_NO_INVITE: { status: 400, message: "Public voice rooms do not require invitations" },
  VOICE_MESSAGE_INVALID: { status: 400, message: "Message body must contain between 1 and 1000 characters" },
  VOICE_ROOM_NOT_IN_PARALLEL_ROOM: { status: 404, message: "Voice room not found in this parallel room" },
  VOICE_MEMBER_NOT_IN_ROOM: { status: 400, message: "Invited user must be an active room member" },
  VOICE_PUBLIC_CREATE_FORBIDDEN: { status: 403, message: "Only a host or cohost can create a managed voice room" },
  VOICE_ROOM_LIMIT_REACHED: { status: 409, message: "This parallel room has reached its active voice room limit" },
  LIVEKIT_NOT_CONFIGURED: { status: 503, message: "LiveKit is not configured on the server" },

  // Assets & storage
  UPLOAD_FIELDS_REQUIRED: { status: 400, message: "worldId, filename, contentType and byteSize are required" },
  FILE_TOO_LARGE: { status: 413, message: "File exceeds account single-file limit" },
  STORAGE_QUOTA_EXCEEDED: { status: 413, message: "Storage quota exceeded" },
  ASSET_VISIBILITY_INVALID: { status: 400, message: "Unsupported visibility" },
  ASSET_KIND_INVALID: { status: 400, message: "Unsupported asset kind" },
  ASSET_ROLE_REQUIRED: { status: 400, message: "roleSlotId is required for role visibility" },
  ASSET_ROOM_WORLD_MISMATCH: { status: 400, message: "roomId does not belong to worldId" },
  ASSET_ROLE_WORLD_MISMATCH: { status: 400, message: "roleSlotId does not belong to worldId" },
  ASSET_NOT_FOUND: { status: 404, message: "Asset not found or permission denied" },
  ASSET_NOT_IN_RECYCLE: { status: 404, message: "Asset is not in recycle bin or purge window expired" },
  UPLOAD_SESSION_NOT_FOUND: { status: 404, message: "Active upload session not found" },
  UPLOAD_SIZE_MISMATCH: { status: 409, message: "Uploaded file size does not match upload request" },
  UPLOAD_TYPE_MISMATCH: { status: 409, message: "Uploaded content type does not match upload request" },
  UPLOAD_SCAN_NOT_CONFIGURED: { status: 503, message: "Upload scan is not configured" },
  UPLOAD_SCAN_FAILED: { status: 502, message: "Upload scan service failed" },
  UPLOAD_SCAN_INFECTED: { status: 422, message: "Uploaded file failed malware scan" },
  UPLOAD_SCAN_SPOOFED: { status: 422, message: "Uploaded file content does not match its declared type" },

  // Ops / metrics
  OPS_NOT_CONFIGURED: { status: 503, message: "Ops API is not configured (set OPS_API_TOKEN)" },
  OPS_TOKEN_REQUIRED: { status: 401, message: "Valid ops token required" },
  OPS_TOKEN_TOO_WEAK: { status: 503, message: "OPS_API_TOKEN is too weak (minimum 16 characters in production)" },
  METRICS_TOKEN_REQUIRED: { status: 401, message: "Valid metrics token required" },
  METRICS_NOT_CONFIGURED: { status: 503, message: "Metrics endpoint is not configured (set METRICS_TOKEN in production)" },

  // Feedback
  FEEDBACK_KIND_INVALID: { status: 400, message: "Kind must be one of: feedback, bug, feature" },
  FEEDBACK_SUBJECT_REQUIRED: { status: 400, message: "Subject is required" },
  FEEDBACK_BODY_REQUIRED: { status: 400, message: "Body is required" },
  FEEDBACK_STATUS_INVALID: { status: 400, message: "Status must be one of: new, seen, resolved" },
  FEEDBACK_NOT_FOUND: { status: 404, message: "Feedback not found" },

  // Story assistant & documents
  STORY_TEXT_REQUIRED: { status: 400, message: "Story draft text is required" },
  STORY_MANUSCRIPT_REQUIRED: { status: 400, message: "Story manuscript body is required" },
  STORY_BLOCKS_EMPTY: { status: 400, message: "No story blocks detected" },
  DEEPSEEK_PACKAGE_REQUIRED: { status: 400, message: "DeepSeek mystery package is required" },
  DEEPSEEK_NOT_CONFIGURED: { status: 503, message: "DeepSeek API 尚未配置。请在 backend/.env 中填写 DEEPSEEK_API_KEY。" },
  LLM_CREDENTIALS_NOT_CONFIGURED: { status: 503, message: "服务器尚未配置 API Key 加密，暂无法保存自备连接" },
  LLM_BASE_URL_UNSAFE: { status: 400, message: "AI baseUrl must use a public HTTPS endpoint" },
  LLM_USER_NOT_CONFIGURED: { status: 403, message: "请先在账号设置中配置自己的 AI API 连接" },
  LLM_PLATFORM_DISABLED: { status: 403, message: "平台 AI 池暂未开放，请使用自己的 API" },
  LLM_NOT_AVAILABLE: { status: 503, message: "AI 暂不可用：请配置自备 API 或联系 support" },
  LLM_PROBE_FAILED: { status: 502, message: "AI 连接测试失败" },
  LLM_RESPONSE_TOO_LARGE: { status: 502, message: "AI provider response exceeds the safe processing limit" },
  DOCUMENT_SIZE_INVALID: { status: 413, message: "Document must contain between 1 byte and 5 MB" },
  DOCUMENT_TYPE_UNSUPPORTED: { status: 415, message: "Only TXT, Markdown, DOCX, PDF and image documents can be parsed" },
  DOCUMENT_ARCHIVE_TOO_LARGE: { status: 413, message: "The DOCX archive expands beyond the safe processing limit" },
  DOCUMENT_TEXT_TOO_LARGE: { status: 413, message: "The extracted document text exceeds the import limit" },
  DOCUMENT_PROCESSING_BUSY: { status: 503, message: "Document processing is busy; retry shortly" },
  DOCUMENT_EMPTY: { status: 422, message: "Document does not contain readable text" },
  DOCUMENT_STRUCTURE_EMPTY: { status: 422, message: "No importable narrative structure was detected" },
  IMPORT_RIGHTS_CONFIRMATION_REQUIRED: { status: 400, message: "请先确认你有权处理和导入该稿件" },
  FEISHU_IMPORT_NOT_CONFIGURED: { status: 503, message: "飞书稿件导入尚未配置" },
  FEISHU_DOCUMENT_URL_INVALID: { status: 400, message: "请输入有效的飞书文档或知识库链接" },
  FEISHU_DOCUMENT_FORBIDDEN: { status: 403, message: "飞书应用无权读取该文档，请先把文档授权给应用" },
  FEISHU_DOCUMENT_NOT_FOUND: { status: 404, message: "飞书文档不存在或已经删除" },
  FEISHU_LEGACY_DOCUMENT_UNSUPPORTED: { status: 422, message: "旧版飞书文档需先升级或复制为新版文档" },
  FEISHU_DOCUMENT_TOO_LARGE: { status: 413, message: "飞书文档超过导入限制" },
  FEISHU_IMPORT_FAILED: { status: 502, message: "飞书文档读取失败，请稍后重试" },
  PDF_PAGES_RECOMMENDED: {
    status: 422,
    message: "PDF has no text layer; use image page import instead"
  },
  PDF_PAGE_IMPORT_LIMIT: { status: 413, message: "PDF exceeds page import limit" },
  PDF_OCR_REQUIRED: {
    status: 422,
    message: "PDF has no text layer; enable PDF OCR or import as image pages"
  },
  PDF_OCR_PAGE_LIMIT: { status: 413, message: "PDF exceeds OCR page limit" },

  SCRIPT_BUNDLE_INVALID: { status: 400, message: "Invalid script bundle zip archive" },
  SCRIPT_BUNDLE_EMPTY: { status: 400, message: "Script bundle zip is empty" },
  SCRIPT_BUNDLE_TOO_LARGE: { status: 413, message: "Script bundle zip exceeds size limit" },
  SCRIPT_BUNDLE_ENTRY_LIMIT: { status: 413, message: "Script bundle has too many files" },
  SCRIPT_BUNDLE_ENTRY_INVALID: { status: 400, message: "Script bundle contains unsafe path entries" },
  SCRIPT_BUNDLE_UNCOMPRESSED_LIMIT: { status: 413, message: "Script bundle uncompressed size exceeds limit" },
  SCRIPT_BUNDLE_NO_SUPPORTED_FILES: { status: 422, message: "Script bundle has no supported files" },
  SCRIPT_BUNDLE_PROCESSING_BUSY: { status: 503, message: "Script bundle processing is busy; retry shortly" },

  // Content package
  CONTENT_PACKAGE_INVALID: { status: 400, message: "A valid Zhimu JSON content package is required" },
  CONTENT_PACKAGE_STRUCTURE_INVALID: { status: 400, message: "Content package must include roles and chapters arrays" },
  CONTENT_PACKAGE_FORMAT_INVALID: { status: 400, message: "Unsupported package format" },
  CONTENT_PACKAGE_VERSION_INVALID: { status: 400, message: "Unsupported package version" },
  CONTENT_PACKAGE_TOO_LARGE: { status: 413, message: "Content package exceeds the supported import limits" },
  CONTENT_PACKAGE_PROCESSING_BUSY: { status: 503, message: "Content package processing is busy; retry shortly" }
};

export function errorMeta(code) {
  return API_ERRORS[code] ?? null;
}
