import { registerWorldRoutes } from "./routes/world-routes.js";
import { registerWorldReadinessRoutes } from "./routes/world-readiness-routes.js";
import { registerWorldWizardRoutes } from "./routes/world-wizard-routes.js";
import { registerCreatorRoutes } from "./routes/creator-routes.js";
import { registerScriptBundleRoutes } from "./routes/script-bundle-routes.js";
import { registerRulesRoutes } from "./routes/rules-routes.js";
import { registerContentPackageRoutes } from "./routes/content-package-routes.js";
import { registerStudioRoutes } from "./routes/studio-routes.js";
import { registerStoryAssistantRoutes } from "./routes/story-assistant-routes.js";
import { registerStudioGraphRoutes } from "./routes/studio-graph-routes.js";
import { registerCheckpointRoutes } from "./routes/checkpoint-routes.js";
import { registerRecapRoutes } from "./routes/recap-routes.js";
import { registerRoomEventsRoutes } from "./routes/room-events-routes.js";
import { registerHostRoutes } from "./routes/host-routes.js";
import { registerPlayerRoutes } from "./routes/player-routes.js";
import { registerVoiceRoutes } from "./routes/voice-routes.js";
import { registerAssetRoutes } from "./routes/asset-routes.js";
import { registerAccountRoutes } from "./routes/account-routes.js";
import { registerPhysicalTokenRoutes } from "./routes/physical-token-routes.js";
import { registerSearchRoutes } from "./routes/search-routes.js";
import { registerFeedbackRoutes } from "./routes/feedback-routes.js";
import { registerBatchBRoutes } from "./routes/batch-b-routes.js";
import { registerContentPlatformRoutes } from "./routes/content-platform-routes.js";
import { registerCreatorBibleRoutes } from "./routes/creator-bible-routes.js";
import { registerCreatorBootstrapRoutes } from "./routes/creator-bootstrap-routes.js";

export async function registerRoutes(app) {
  await registerWorldRoutes(app);
  await registerWorldReadinessRoutes(app);
  await registerWorldWizardRoutes(app);
  await registerCreatorRoutes(app);
  await registerScriptBundleRoutes(app);
  await registerRulesRoutes(app);
  await registerContentPackageRoutes(app);
  await registerStudioRoutes(app);
  await registerStoryAssistantRoutes(app);
  await registerStudioGraphRoutes(app);
  await registerSearchRoutes(app);
  await registerHostRoutes(app);
  await registerCheckpointRoutes(app);
  await registerRecapRoutes(app);
  await registerRoomEventsRoutes(app);
  await registerPlayerRoutes(app);
  await registerVoiceRoutes(app);
  await registerAssetRoutes(app);
  await registerAccountRoutes(app);
  await registerPhysicalTokenRoutes(app);
  await registerFeedbackRoutes(app);
  await registerBatchBRoutes(app);
  await registerContentPlatformRoutes(app);
  await registerCreatorBibleRoutes(app);
  await registerCreatorBootstrapRoutes(app);
}
