/**
 * Murder-mystery mechanism direction catalog.
 * Kits seed the creator workbench; they are not a second runtime.
 */

import {
  DEFAULT_MECHANISM_INTERACTION_KIND,
  isMechanismInteractionKind,
} from "./mechanism-interactions.js";
import { CURRENCY_RESOURCE_KEY } from "./mechanism-package.js";
import { MINI_GAME_PLUGIN_KEYS } from "./mini-game-protocol.js";

export const MECHANISM_CATALOG_VERSION = 1;

function kit(row) {
  return Object.freeze({
    ...row,
    genres: Object.freeze([...(row.genres || [])]),
    suggestedResources: Object.freeze([...(row.suggestedResources || [])]),
    bibleHooks: Object.freeze([...(row.bibleHooks || [])]),
    hostHooks: Object.freeze([...(row.hostHooks || [])]),
    sevenQuestionSeeds: Object.freeze({ ...(row.sevenQuestionSeeds || {}) }),
    pitfalls: Object.freeze([...(row.pitfalls || [])]),
  });
}

export const MECHANISM_KIT_TEMPLATES = Object.freeze([
  kit({
    key: "permission_swap",
    label: "权限交换",
    family: "权限交换",
    genres: ["调查", "政治", "机构"],
    summary: "用一项世界内权限换取另一项访问；交换必须留下可追溯后果。",
    interactionKind: "resource_tradeoff",
    suggestedResources: ["pass", "seat", "clearance"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["authorization_matrix"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "用一项签字权、通行证或席位，换取另一处访问或阅览资格。",
      conflictReason: "权限不能叠加；一人获得访问，另一人必然失去同等资格。",
      limitedResource: "本局可转让的正式权限名额（签字权 / 通行证 / 席位）。",
      immediateFeedback: "权限清单即时更新；被换出的门、档案或席位立刻关闭。",
      failureAdvance: "交换失败时公开一次议价痕迹，并迫使双方改走更高风险路径。",
      genreSpecificity: "依赖本作制度：谁有权签发、谁能撤销、撤销会留什么记录。",
      endingCausality: "早期交换写入的权限持有者，会决定终局谁能进入关键区域或作证。",
    },
    pitfalls: ["把权限写成换皮积分", "交换没有留档或不可撤销说明"],
    example: "用值班签字权换取冷柜登记阅览；签字权转给对方后，本方失去当晚封存权。",
  }),
  kit({
    key: "resource_allocation",
    label: "资源分配",
    family: "资源分配",
    genres: ["灾难", "经营", "机构"],
    summary: "把有限世界资源分给地点或角色；不存在无脑最优解。",
    interactionKind: "numeric_allocation",
    suggestedResources: [CURRENCY_RESOURCE_KEY, "oxygen", "power"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["resource_registry"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "每轮把有限额度分配给地点、角色或设施。",
      conflictReason: "总额固定，保住一处必然削弱另一处。",
      limitedResource: "氧气、床位、电量、银两或其他题材内配额。",
      immediateFeedback: "未获分配的区域立刻失去设施、证据或人员状态。",
      failureAdvance: "超时或分配无效时按默认方案执行，并扩大一处损失。",
      genreSpecificity: "资源名与获取方式必须属于本作世界，不能是通用行动点。",
      endingCausality: "前几轮保留的区域与资源，共同决定终局可走路线。",
    },
    pitfalls: ["存在唯一最优分配", "失败无事发生"],
    example: "三份开闸许可分给救人、保电、保现场；未保护区域当场损失。",
  }),
  kit({
    key: "evidence_qualification",
    label: "证据资格",
    family: "证据资格",
    genres: ["法庭", "调查", "政治程序"],
    summary: "质证来源、程序或保管链；成功与失败都改变材料效力。",
    interactionKind: "evidence_selection",
    suggestedResources: ["objection", "statement_time"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["evidence_lock", "evidence_unlock"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "针对一份材料提出具体程序或来源异议。",
      conflictReason: "异议次数有限；保护自己的材料会放过对手的材料。",
      limitedResource: "正式异议次数或法定陈述时间。",
      immediateFeedback: "材料被暂缓采纳、继续生效，或开放来源复核。",
      failureAdvance: "异议失败时材料继续生效，但留下可上诉的程序记录。",
      genreSpecificity: "依赖本作程序规则：谁有权判定来源与保管链。",
      endingCausality: "被采纳或封存的材料组合，决定终局可成立的指控。",
    },
    pitfalls: ["把异议写成普通投票", "成功才推进、失败无事发生"],
    example: "对医疗记录提出来源异议，消耗一次陈述时间，换取冷柜原始登记。",
  }),
  kit({
    key: "timed_comms",
    label: "限时通讯",
    family: "限时通讯",
    genres: ["谍战", "灾难", "科技"],
    summary: "在暴露前发送或验证消息；超时也要能继续推进。",
    interactionKind: "timed_crisis",
    suggestedResources: ["signal_window", "cipher_use"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["round_clock"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "在时间窗内发送、截获或验证一条消息。",
      conflictReason: "窗口短暂；救人通讯与保密通讯互相挤占。",
      limitedResource: "通讯时间窗、暗号次数或暴露风险。",
      immediateFeedback: "消息送达、被截获，或超时按默认文本发出。",
      failureAdvance: "超时不卡线：默认消息发出并提高暴露等级。",
      genreSpecificity: "依赖本作通讯制度、频道或密码规则。",
      endingCausality: "早期发出或压下的消息，改变终局谁掌握主动叙事。",
    },
    pitfalls: ["失败直接断线卡局", "时限只是气氛没有结算"],
    example: "十八分钟内确认代理授权；超时按默认承认推进并收窄申诉范围。",
  }),
  kit({
    key: "binding_promise",
    label: "承诺契约",
    family: "承诺契约",
    genres: ["社交", "政治", "家庭"],
    summary: "作出可被后续验证的承诺；违约必须有可读后果。",
    interactionKind: "role_commitment",
    suggestedResources: ["guarantee", "voucher"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["role_disclosure"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "当众或私下作出一项可被验证的承诺。",
      conflictReason: "承诺绑定资源或立场；履约与违约都会伤害不同关系。",
      limitedResource: "保证名额、担保额度或信誉窗口。",
      immediateFeedback: "承诺写入公开记录或私人契约，并锁定一项行动资格。",
      failureAdvance: "违约时触发公开羞辱、赔偿或权限收回，但剧情继续。",
      genreSpecificity: "契约形式属于本作习俗、法律或组织纪律。",
      endingCausality: "履约/违约记录被终局结局读取，改变站队与尾声。",
    },
    pitfalls: ["承诺没有违约后果", "承诺无法被局内验证"],
    example: "担保对方不离开宴会；对方离席则担保人失去终局发言席。",
  }),
  kit({
    key: "asymmetric_intel",
    label: "非对称信息",
    family: "非对称信息",
    genres: ["谍战", "社交", "调查"],
    summary: "选择交换、公开或保留信息；不分享不能总是最优。",
    interactionKind: "secret_ballot",
    suggestedResources: ["private_channel", "read_pass"],
    miniGamePluginKey: null,
    bibleHooks: ["material_booklet"],
    hostHooks: ["private_submission"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "选择交换、公开或保留一条只有自己知道的信息。",
      conflictReason: "公开可换取同盟，但会失去独有优势。",
      limitedResource: "私人频道次数、阅览资格或可信度。",
      immediateFeedback: "信息出现在公共桌、指定角色或仍仅自己可见。",
      failureAdvance: "拒绝分享时，环境或其他角色抢先公开扭曲版本。",
      genreSpecificity: "信息渠道属于本作通讯、日记或组织密报。",
      endingCausality: "谁在何时知道真相，决定终局指控与误导是否成立。",
    },
    pitfalls: ["不分享信息成为唯一最优", "私人信息无人可验证"],
    example: "日记页可给一人阅读；不给则主持人在下轮公开被篡改摘要。",
  }),
  kit({
    key: "space_access",
    label: "空间访问",
    family: "空间访问",
    genres: ["搜证", "灾难", "机构"],
    summary: "打开、封锁或放弃区域；地图必须改变可行动作而非菜单。",
    interactionKind: "group_choice",
    suggestedResources: ["key", "power_loop", "search_token"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["investigation_cost", "location_discovery"],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "选择打开、封锁或放弃一个区域的访问。",
      conflictReason: "钥匙与供电有限；开放一处会关闭或削弱另一处。",
      limitedResource: "钥匙、供电回路或通行许可。",
      immediateFeedback: "区域可搜、封锁或耗尽；玩家立刻看到进出变化。",
      failureAdvance: "放弃区域后，该处线索按残缺或污染版本进入公共池。",
      genreSpecificity: "空间结构与安防属于本作建筑与制度。",
      endingCausality: "早期开放/封锁的区域集合，限制终局可呈堂的物证。",
    },
    pitfalls: ["地图只是章节菜单", "搜刮无耗尽"],
    example: "东厢只能搜两次；第三次只能拿到被调包后的残页。",
  }),
  kit({
    key: "public_narrative",
    label: "公众叙事",
    family: "公众叙事",
    genres: ["传媒", "政治", "综艺"],
    summary: "决定公开内容与呈现顺序；叙事权本身是资源。",
    interactionKind: "free_ranking",
    suggestedResources: ["airtime", "edit_right"],
    miniGamePluginKey: "zhimu_sequence",
    bibleHooks: [],
    hostHooks: [],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "决定本轮公开哪些事实以及呈现顺序。",
      conflictReason: "播出时长有限；强调一事必然压缩另一事。",
      limitedResource: "剪辑权、播出时长或热搜位。",
      immediateFeedback: "公共叙事板更新；观众/其他角色态度立刻偏移。",
      failureAdvance: "放弃剪辑权时，系统按敌对版本播出并留下记录。",
      genreSpecificity: "媒体或公审制度是本作世界规则的一部分。",
      endingCausality: "累计播出框架决定终局公众接受哪条真相。",
    },
    pitfalls: ["退化成支持率数值", "顺序不影响可执行结果"],
    example: "四条新闻只能排三个播出位；未播出者成为终局黑料。",
  }),
  kit({
    key: "sacrifice_slot",
    label: "替代与牺牲",
    family: "替代与牺牲",
    genres: ["灾难", "家庭", "军事"],
    summary: "用一项资格替代另一项；牺牲必须被后续读取。",
    interactionKind: "role_commitment",
    suggestedResources: ["evac_seat", "substitute_slot"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["ending_route"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "选择用谁的资格替代谁，或放弃自己的撤离席。",
      conflictReason: "席位不足；保全一人会让另一人失去资格。",
      limitedResource: "替补名额、撤离座位或豁免次数。",
      immediateFeedback: "席位名单更新；被牺牲者立刻失去对应行动权。",
      failureAdvance: "无人牺牲时系统抽签并公开抽签记录。",
      genreSpecificity: "替代规则来自本作纪律、亲缘或军事条例。",
      endingCausality: "牺牲记录改写终局谁能在场、谁承担罪名。",
    },
    pitfalls: ["牺牲没有后续读取", "总有人自愿且无代价"],
    example: "把撤离席让给证人；自己留下并在终局无法亲自对质。",
  }),
  kit({
    key: "memory_reframe",
    label: "记忆重构",
    family: "记忆重构",
    genres: ["超自然", "心理", "科幻"],
    summary: "恢复、公开或覆盖记忆片段；记忆不可当作客观唯一真相。",
    interactionKind: "sequence_reconstruction",
    suggestedResources: ["recall_charge", "overwrite_token"],
    miniGamePluginKey: "zhimu_sequence",
    bibleHooks: ["material_booklet", "appearance_matrix"],
    hostHooks: [],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "选择恢复、公开或覆盖一段记忆/日记片段。",
      conflictReason: "恢复次数有限；公开真实记忆会暴露自己。",
      limitedResource: "可恢复片段次数或读取权限。",
      immediateFeedback: "角色可知信息或外形认知更新；冲突版本并存。",
      failureAdvance: "覆盖失败时两套记忆同时公开，迫使当众对质。",
      genreSpecificity: "记忆介质（药、装置、日记）属于本作设定。",
      endingCausality: "哪套记忆被多数人采信，决定终局身份与罪责。",
    },
    pitfalls: ["记忆被当成客观真相", "无冲突版本可对质"],
    example: "按日恢复外形记忆；D2 与 D3 冲突时必须公开其中一日日记。",
  }),
  kit({
    key: "auction_exchange",
    label: "竞价与交换",
    family: "竞价与交换",
    genres: ["青楼", "商战", "社交"],
    summary: "用真实筹码争夺稀缺机会；需防私下合谋让系统失效。",
    interactionKind: "numeric_allocation",
    suggestedResources: [CURRENCY_RESOURCE_KEY, "favor"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["currency_ledger", "cohost"],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "对稀缺席位、线索或服务出价，或用筹码交换。",
      conflictReason: "筹码总量有限；抬价会挤出其他买家。",
      limitedResource: "银两、人情或可转让承诺。",
      immediateFeedback: "成交价入账；未得标者失去本轮机会但保留筹码。",
      failureAdvance: "流拍时物品进入公共池或由主持人按底价强制成交。",
      genreSpecificity: "计价物与拍卖规矩来自本作宴会或市集制度。",
      endingCausality: "谁在拍卖中拿下关键物，改变终局可呈堂证据。",
    },
    pitfalls: ["私下合谋使竞价失效", "货币只是装饰无结算"],
    example: "花魁夜竞拍密信；第二名支付差价获得残页。",
  }),
  kit({
    key: "rotating_duty",
    label: "轮值职责",
    family: "轮值职责",
    genres: ["机构", "军事", "校园"],
    summary: "不同角色轮流掌握决定权；轮值必须改变实际能力。",
    interactionKind: "group_choice",
    suggestedResources: ["duty_shift", "veto_window"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["cohost", "authorization_matrix"],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "在值班时段作出只有值日者能做的决定。",
      conflictReason: "否决窗口与值班互斥；不当班者无法直接否决。",
      limitedResource: "值班时段、否决窗口或交接印章。",
      immediateFeedback: "值日权限清单切换；过期动作自动失效。",
      failureAdvance: "无人接班时系统指定代理并公开代理记录。",
      genreSpecificity: "轮班制度属于本作组织纪律。",
      endingCausality: "谁在关键夜值班，决定谁能为关键操作背书。",
    },
    pitfalls: ["轮值不改变实际能力", "永远同一人实质掌权"],
    example: "双主持分管拍卖与搜证；错班操作必须重做并留痕。",
  }),
  kit({
    key: "search_depletion",
    label: "搜证耗尽",
    family: "空间访问",
    genres: ["搜证", "本格", "机构"],
    summary: "地点可搜次数与搜证成本绑定；搜空后只剩残缺或污染结果。",
    interactionKind: "evidence_selection",
    suggestedResources: ["search_token", CURRENCY_RESOURCE_KEY],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["investigation_cost", "investigation_max_uses"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "消耗搜证次数或代币，对指定地点执行一次搜查。",
      conflictReason: "次数耗尽后无法再拿完整物证；多人抢同一热点。",
      limitedResource: "搜证代币、行动次数或银两。",
      immediateFeedback: "地点剩余次数下降；成功解锁证据，失败留下翻动痕迹。",
      failureAdvance: "次数用尽后仍可“强搜”，但只得到误导或残页。",
      genreSpecificity: "地点与搜查方法属于本作场景设计。",
      endingCausality: "哪些地点被搜空，决定终局证据完整度。",
    },
    pitfalls: ["无限搜刮", "成本不入账"],
    example: "花房只能有效搜查两次；第三次强制得到调包后的花名录残页。",
  }),
  kit({
    key: "clue_destroy_forge",
    label: "毁证与伪造",
    family: "证据资格",
    genres: ["青楼", "谍战", "权谋"],
    summary: "授权销毁或伪造线索；必须留审计痕迹，避免无成本改写真相。",
    interactionKind: "evidence_selection",
    suggestedResources: ["yamen_order", "forge_ink"],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["evidence_lock", "cohost", "action_log"],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "出示令牌后销毁、封存或替换一份已公开线索。",
      conflictReason: "令牌稀缺；销毁敌证同时可能毁掉自己需要的旁证。",
      limitedResource: "衙门令、伪造墨或可销毁次数。",
      immediateFeedback: "目标线索标记为已毁/伪造；主持端留下不可擦审计。",
      failureAdvance: "伪造被识破时，原件与伪件同时公开。",
      genreSpecificity: "谁有权签发销毁令，来自本作官府或组织设定。",
      endingCausality: "被毁与被伪线索集合，改变终局可引用证据。",
    },
    pitfalls: ["无审计销毁", "伪造无识破路径"],
    example: "衙门令可毁一张账本；销毁后主持手册仍保留真账供复盘。",
  }),
  kit({
    key: "identity_appearance",
    label: "身份外形矩阵",
    family: "记忆重构",
    genres: ["换身", "奇幻", "本格"],
    summary: "真实身份固定，外形按幕/日变化；玩家认知与真相分层。",
    interactionKind: "group_choice",
    suggestedResources: [],
    miniGamePluginKey: null,
    bibleHooks: ["appearance_matrix", "role_archive"],
    hostHooks: ["cohost"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "按当前日/幕的外形互动，并决定是否试探真实身份。",
      conflictReason: "外形可信会误导搜证；公开真实身份会失去伪装优势。",
      limitedResource: "可公开的真实身份次数或对质窗口。",
      immediateFeedback: "当日外形与可知信息刷新；错认会写入公开记录。",
      failureAdvance: "对质失败时强制公开一对冲突外形日。",
      genreSpecificity: "换身规则必须是本作世界法则，而非装饰性变装。",
      endingCausality: "各日外形与真身对齐结果，决定终局指认是否成立。",
    },
    pitfalls: ["只有真身没有日程外形", "外形变化不影响可执行信息"],
    example: "换身本：D1–D3 外形表写入角色档案，真身仅主持与本人可见。",
  }),
  kit({
    key: "parallel_booklet",
    label: "平行物料册",
    family: "非对称信息",
    genres: ["本格", "情感", "奇幻"],
    summary: "日记/图鉴/手册作为一等物料，不降级成单条线索。",
    interactionKind: "evidence_selection",
    suggestedResources: ["read_pass"],
    miniGamePluginKey: null,
    bibleHooks: ["material_booklet"],
    hostHooks: ["clue_grant"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "打开或转交一册完整物料（日记、花草录、镜目录等）。",
      conflictReason: "整册阅读耗时；转交会让对方掌握完整语境。",
      limitedResource: "可读页数、转交次数或公开桌席位。",
      immediateFeedback: "指定角色获得册内页；其余人仍只见封皮或摘要。",
      failureAdvance: "未读完时主持人公开被裁切的误导摘要。",
      genreSpecificity: "册子介质与阅读规矩属于本作物料设计。",
      endingCausality: "谁读过完整册，决定终局能否拼出隐藏关系。",
    },
    pitfalls: ["把整册拆成互不关联线索", "无归属与阶段"],
    example: "镜目录整册挂平行物料；局内仍用线索卡发放单页摘录。",
  }),
  kit({
    key: "song_guess",
    label: "歌猜 / 口令还原",
    family: "限时通讯",
    genres: ["娱乐", "奇幻", "聚会"],
    summary: "听曲或口令猜题；用小游戏插件承载，失败可主持恢复。",
    interactionKind: "timed_crisis",
    suggestedResources: ["guess_attempt"],
    miniGamePluginKey: "zhimu_guess",
    bibleHooks: [],
    hostHooks: ["mini_game"],
    capability: "partial",
    sevenQuestionSeeds: {
      recurringAction: "在时限内根据歌词、旋律或口令提交猜测。",
      conflictReason: "尝试次数有限；猜错会消耗次数并暴露方向。",
      limitedResource: "猜测次数或限时秒数。",
      immediateFeedback: "对则解锁下一机关；错则减少次数并给出弱提示。",
      failureAdvance: "次数耗尽后主持可恢复或改发残缺奖励。",
      genreSpecificity: "曲目或口令必须嵌入本作故事，而非无关小游戏。",
      endingCausality: "是否解开歌谜，决定能否取得关键信物。",
    },
    pitfalls: ["小游戏与主线无关", "失败卡死无法主持恢复"],
    example: "听曲猜曲名，解开后发放镜片线索。",
  }),
  kit({
    key: "lock_device",
    label: "机关密码锁",
    family: "空间访问",
    genres: ["搜证", "机关", "本格"],
    summary: "数字或符号锁；答案来自局内线索，不来自场外知识。",
    interactionKind: "timed_crisis",
    suggestedResources: ["lock_attempt"],
    miniGamePluginKey: "zhimu_lock",
    bibleHooks: [],
    hostHooks: ["mini_game"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "根据已得线索输入机关密码。",
      conflictReason: "尝试次数有限；错试会触发警报或损失。",
      limitedResource: "开锁尝试次数或警报阈值。",
      immediateFeedback: "开启容器、触发陷阱或锁死等待主持。",
      failureAdvance: "锁死后主持可恢复机会，或改发破损内容。",
      genreSpecificity: "密码来源必须能在本作线索中拼出。",
      endingCausality: "是否开启机关，决定关键物证是否入局。",
    },
    pitfalls: ["密码靠场外常识", "无线索可推导"],
    example: "四位柜锁密码来自三张散落收据末位。",
  }),
  kit({
    key: "sequence_device",
    label: "顺序机关",
    family: "空间访问",
    genres: ["搜证", "机关", "本格"],
    summary: "按正确步骤还原流程；适合歌单、药方、操作规程。",
    interactionKind: "sequence_reconstruction",
    suggestedResources: ["sequence_attempt"],
    miniGamePluginKey: "zhimu_sequence",
    bibleHooks: [],
    hostHooks: ["mini_game"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "按正确顺序提交一组操作或事件步骤。",
      conflictReason: "步骤信息分散在不同角色；单独一人难以凑齐。",
      limitedResource: "提交次数或试错惩罚。",
      immediateFeedback: "顺序正确则开启下一环；错误则打乱或扣次数。",
      failureAdvance: "失败后可获得局部正确提示，但不直接给完整答案。",
      genreSpecificity: "步骤内容必须来自本作物料与剧情。",
      endingCausality: "是否还原完整流程，决定关键真相是否可当众演示。",
    },
    pitfalls: ["顺序可穷举无惩罚", "步骤与故事无关"],
    example: "药方三步必须按日记记载顺序提交。",
  }),
  kit({
    key: "dual_host_split",
    label: "双主持分工",
    family: "轮值职责",
    genres: ["大型本", "公演", "青楼"],
    summary: "主主持与协管分工结算；关键操作需审计，避免单点失误。",
    interactionKind: "group_choice",
    suggestedResources: [],
    miniGamePluginKey: null,
    bibleHooks: [],
    hostHooks: ["cohost", "action_log"],
    capability: "ready",
    sevenQuestionSeeds: {
      recurringAction: "由主主持与协管分别确认搜证、拍卖或宣判步骤。",
      conflictReason: "两人职责互斥；越权操作必须回滚并留痕。",
      limitedResource: "各自分管的确认窗口。",
      immediateFeedback: "操作日志显示确认人；未会签动作不生效。",
      failureAdvance: "一人失联时启用代理规则并公开代理声明。",
      genreSpecificity: "双主持来自本作场控需要，而非装饰性头衔。",
      endingCausality: "会签记录保证终局宣判可审计、可复盘。",
    },
    pitfalls: ["协管无实权", "无操作日志"],
    example: "一人管拍卖账本，一人管搜证令牌。",
  }),
]);

const KIT_BY_KEY = new Map(MECHANISM_KIT_TEMPLATES.map((row) => [row.key, row]));

export function listMechanismKits({ genre = "", capability = "" } = {}) {
  const genreNeedle = String(genre ?? "").trim();
  const capabilityNeedle = String(capability ?? "").trim();
  return MECHANISM_KIT_TEMPLATES.filter((row) => {
    if (capabilityNeedle && row.capability !== capabilityNeedle) return false;
    if (!genreNeedle) return true;
    return row.genres.some(
      (item) => item.includes(genreNeedle) || genreNeedle.includes(item),
    );
  });
}

export function getMechanismKit(key) {
  return KIT_BY_KEY.get(String(key ?? "").trim()) || null;
}

export function isMechanismKitKey(key) {
  return KIT_BY_KEY.has(String(key ?? "").trim());
}

export function applyMechanismKitToDesign(design = {}, kitKey = "") {
  const selected = getMechanismKit(kitKey);
  if (!selected) {
    return {
      ...design,
      templateKey: String(design?.templateKey ?? "").trim(),
    };
  }
  const interactionKind = isMechanismInteractionKind(selected.interactionKind)
    ? selected.interactionKind
    : DEFAULT_MECHANISM_INTERACTION_KIND;
  const seeds = selected.sevenQuestionSeeds || {};
  return {
    ...design,
    templateKey: selected.key,
    interactionKind,
    title: design.title || selected.label,
    summary: design.summary || selected.summary,
    recurringAction: design.recurringAction || seeds.recurringAction || "",
    conflictReason: design.conflictReason || seeds.conflictReason || "",
    limitedResource: design.limitedResource || seeds.limitedResource || "",
    immediateFeedback: design.immediateFeedback || seeds.immediateFeedback || "",
    failureAdvance: design.failureAdvance || seeds.failureAdvance || "",
    genreSpecificity: design.genreSpecificity || seeds.genreSpecificity || "",
    endingCausality: design.endingCausality || seeds.endingCausality || "",
  };
}

export function mechanismKitMiniGameKey(kitKey) {
  const selected = getMechanismKit(kitKey);
  if (!selected?.miniGamePluginKey) return null;
  return MINI_GAME_PLUGIN_KEYS.includes(selected.miniGamePluginKey)
    ? selected.miniGamePluginKey
    : null;
}

export function mechanismCatalogFamilies() {
  return [...new Set(MECHANISM_KIT_TEMPLATES.map((row) => row.family))];
}
