import assert from "node:assert/strict";
import test from "node:test";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("production build artifacts exist after vite build", (context) => {
  const distIndex = path.join(root, "dist", "index.html");
  if (!existsSync(distIndex)) {
    context.skip("host/dist is generated by the preceding production build gate");
    return;
  }
  const html = readFileSync(distIndex, "utf8");
  const assets = readdirSync(path.join(root, "dist", "assets"));
  assert.match(html, /织幕 · 主持端/);
  assert.match(html, /assets\/index-.*\.js/);
  assert.ok(assets.some((name) => /^console-.*\.js$/.test(name)), "missing lazy console view chunk");
  assert.ok(
    assets.some((name) => /^host-console-runtime-.*\.js$/.test(name)),
    "missing lazy console action runtime chunk"
  );
  assert.ok(assets.some((name) => /^console-.*\.css$/.test(name)), "missing lazy console workspace styles");
});

test("index.html uses module entry without inline scripts", () => {
  const html = readFileSync(path.join(root, "index.html"), "utf8");
  assert.match(html, /src="\/src\/main\.js"/);
  assert.doesNotMatch(html, /<script(?![^>]*type="module")[^>]*>/);
});

test("host api uses cookie credentials, bearer fallback and room-scoped host endpoints", () => {
  const apiSource = readFileSync(path.join(root, "src", "api.js"), "utf8");
  const sessionSource = readFileSync(path.join(root, "src", "session.js"), "utf8");
  const sharedFetchSource = readFileSync(path.join(root, "..", "shared", "api-fetch.js"), "utf8");
  const sharedSseSource = readFileSync(path.join(root, "..", "shared", "sse-client.js"), "utf8");
  const sharedTokenSource = readFileSync(path.join(root, "..", "shared", "session-token.js"), "utf8");
  assert.match(apiSource, /getHostPlayers/);
  assert.match(apiSource, /streamRoomEvents/);
  assert.match(apiSource, /getWorldSegments/);
  assert.match(apiSource, /getHostOrigin/);
  assert.match(apiSource, /createPortalApiClient/);
  assert.match(apiSource, /defaultSessionTokenStore/);
  assert.match(apiSource, /createRoom/);
  assert.match(apiSource, /createRoom:[\s\S]{0,300}idempotent:\s*true[\s\S]{0,100}idempotencyKey/);
  assert.match(apiSource, /hostCreateVote:[\s\S]{0,300}idempotent:\s*true[\s\S]{0,100}idempotencyKey/);
  assert.match(apiSource, /streamRoomEvents/);
  assert.match(apiSource, /hostClueNote:[\s\S]{0,200}method:\s*"PUT"[\s\S]{0,120}idempotent:\s*true/);
  assert.match(apiSource, /createCheckpoint:[\s\S]{0,260}idempotent:\s*true[\s\S]{0,120}timeoutMs:\s*45_000/);
  assert.match(apiSource, /createRecap:[\s\S]{0,260}idempotent:\s*true[\s\S]{0,120}timeoutMs:\s*45_000/);
  assert.match(apiSource, /getRoomCheckpoints/);
  assert.match(apiSource, /getRoomRecaps/);
  assert.match(sharedSseSource, /openSseStream/);
  assert.match(sharedSseSource, /message\?\.type === "connected"/);
  assert.match(sharedSseSource, /message\?\.type === "heartbeat"/);
  assert.match(sharedSseSource, /Last-Event-ID/);
  assert.match(sharedFetchSource, /credentials = "include"/);
  assert.match(sharedTokenSource, /setItem\(key, token\)/);
  assert.match(sessionSource, /defaultSessionTokenStore/);
});

test("main.js wires console, SSE and director actions", () => {
  const mainSource = readFileSync(path.join(root, "src", "main.js"), "utf8");
  const directorSource = readFileSync(path.join(root, "src", "runtime", "director-actions.js"), "utf8");
  const lifecycleSource = readFileSync(path.join(root, "src", "runtime", "host-lifecycle-controller.js"), "utf8");
  const shellSource = readFileSync(path.join(root, "src", "components", "shell.js"), "utf8");
  const consoleLoaderSource = readFileSync(path.join(root, "src", "runtime", "host-console-loader.js"), "utf8");
  const consoleRuntimeSource = readFileSync(path.join(root, "src", "runtime", "host-console-runtime.js"), "utf8");
  const consoleSource = readFileSync(path.join(root, "src", "views", "console.js"), "utf8");
  const dataSource = readFileSync(path.join(root, "src", "runtime", "data.js"), "utf8");
  const eventsSource = readFileSync(path.join(root, "src", "runtime", "room-events.js"), "utf8");
  const archiveSource = readFileSync(path.join(root, "src", "runtime", "host-archive-controller.js"), "utf8");
  const eventWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-event-workspace-controller.js"), "utf8");
  const operationSource = readFileSync(path.join(root, "src", "runtime", "host-operation-controller.js"), "utf8");
  const ruleWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-rule-workspace-controller.js"), "utf8");
  const voteWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-vote-workspace-controller.js"), "utf8");
  assert.match(eventsSource, /connectRoomEvents/);
  assert.match(eventsSource, /room\.content_release_changed/);
  assert.doesNotMatch(directorSource, /executeHostEvent|dismissHostEvent|delayHostEvent|window\.prompt/);
  assert.match(eventWorkspaceSource, /case "host-event-workspace-submit"/);
  assert.match(directorSource, /case "host-select-act"/);
  assert.match(directorSource, /el\?\.dataset\?\.actKey/);
  assert.match(operationSource, /clueId:\s*element\?\.dataset\?\.clueId/);
  assert.match(operationSource, /roleKey:\s*element\?\.dataset\?\.roleKey/);
  assert.match(operationSource, /HOST_OPERATION_KINDS\.UNLOCK_SECTION/);
  assert.doesNotMatch(`${mainSource}\n${directorSource}`, /button\.dataset\.(?:testimony|flag|remedy|voteId|status|actionId|actKey)/);
  assert.match(mainSource, /renderApp/);
  assert.match(lifecycleSource, /requestMe:\s*api\.me/);
  assert.match(lifecycleSource, /await loadHostConsole\(\{ render, showToast \}\)/);
  assert.doesNotMatch(shellSource, /from\s+["'][^"']*views\/console\.js["']/);
  assert.match(shellSource, /renderHostConsoleBoundary/);
  assert.match(consoleLoaderSource, /import\(["']\.\.\/views\/console\.js["']\)/);
  assert.match(consoleLoaderSource, /import\(["']\.\/host-console-runtime\.js["']\)/);
  assert.match(consoleLoaderSource, /consolePromise = null/);
  assert.doesNotMatch(mainSource, /host-(?:archive|event|operation|rule|vote)-workspace\.css/);
  assert.match(consoleSource, /host-archive-workspace\.css/);
  assert.match(consoleSource, /host-operation-workspace\.css/);
  assert.match(consoleSource, /host-rule-workspace\.css/);
  assert.match(consoleSource, /host-event-workspace\.css/);
  assert.match(consoleSource, /host-vote-workspace\.css/);
  assert.match(
    lifecycleSource,
    /import\s*\{[^}]*\bgetSessionToken\b[^}]*\}\s*from\s*["']\.\.\/session\.js["']/s
  );
  assert.doesNotMatch(`${mainSource}\n${lifecycleSource}`, /if \(!getSessionToken\(\)\) return/);
  assert.match(mainSource, /createHostLifecycleController\(\{ render, setBusy, showToast: setToast \}\)/);
  assert.match(mainSource, /handleHostConsoleAction\(action, button\)/);
  assert.match(mainSource, /handleHostConsoleField\(event\.target\)/);
  assert.match(mainSource, /beforeunload/);
  assert.match(lifecycleSource, /blockUnsafeConsoleExit/);
  assert.match(consoleRuntimeSource, /createDirectorActionHandler\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /createHostOperationController\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /createHostArchiveController\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /createHostRuleWorkspaceController\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /createHostEventWorkspaceController\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /createHostVoteWorkspaceController\(\{ render, showToast \}\)/);
  assert.match(consoleRuntimeSource, /hostOperations\.handleField\(element\)/);
  assert.match(consoleRuntimeSource, /hostArchive\.handleField\(element\)/);
  assert.match(consoleRuntimeSource, /hostRules\.handleField\(element\)/);
  assert.match(consoleRuntimeSource, /hostEvents\.handleField\(element\)/);
  assert.match(consoleRuntimeSource, /hostVotes\.handleField\(element\)/);
  assert.match(archiveSource, /case "create-checkpoint"/);
  assert.match(archiveSource, /case "create-recap"/);
  assert.match(ruleWorkspaceSource, /case "host-rule-save"/);
  assert.match(voteWorkspaceSource, /case "host-vote-workspace-submit"/);
  assert.match(directorSource, /createDirectorActionHandler\(\{ render, showToast \}\)/);
  assert.doesNotMatch(directorSource, /\bsetToast\(/);
  assert.match(consoleSource, /renderConsole/);
  assert.match(consoleSource, /host-kick-player/);
  assert.match(dataSource, /api\.getWorldSegments\(worldId\)/);
  assert.match(eventsSource, /room\.host_event_pending/);
  assert.match(eventsSource, /createPortalEventLifecycle/);
  assert.match(eventsSource, /refresh:\s*refreshDirectorPoll/);
  assert.match(eventsSource, /onAuthLost/);
  assert.match(eventsSource, /refreshOpenPlayerOperation/);
  assert.doesNotMatch(eventsSource, /state\.roomEventsConnected && getRoomId\(\) === boundRoom/);
});

test("web vitals are reported to the shared app backend", () => {
  const lifecycleSource = readFileSync(path.join(root, "src", "runtime", "host-lifecycle-controller.js"), "utf8");
  assert.match(lifecycleSource, /getAppOrigin/);
  assert.match(lifecycleSource, /endpoint:\s*`\$\{getAppOrigin\(\)\}\/api\/metrics\/web-vitals`/);
  assert.doesNotMatch(lifecycleSource, /endpoint:\s*["']\/api\/metrics\/web-vitals["']/);
});

test("host command center uses segment runbooks and five critical queue actions", () => {
  const layoutSource = readFileSync(path.join(root, "src", "views", "host-layout.js"), "utf8");
  const directorSource = readFileSync(path.join(root, "src", "runtime", "director-actions.js"), "utf8");
  const stylesSource = readFileSync(path.join(root, "src", "styles.css"), "utf8");
  assert.match(layoutSource, /state\.cloudWorldSegments/);
  assert.match(layoutSource, /export function hostRunbooks/);
  assert.match(layoutSource, /resolveChapterSegmentKey/);
  assert.match(layoutSource, /segmentRunbookFromOperations/);
  assert.match(layoutSource, /runbook\?\.fallbacks/);
  assert.match(layoutSource, /state\.cloudHostClueMatrix/);
  assert.match(layoutSource, /function grantStatus/);
  assert.match(layoutSource, /renderPlayerTasks/);
  assert.match(layoutSource, /runbook\?\.playerTasks/);
  assert.match(layoutSource, /data-clue-id/);
  assert.match(layoutSource, /data-role-key/);
  assert.match(layoutSource, /解锁本幕分幕/);
  assert.match(layoutSource, /renderHostCommandCenter/);
  assert.match(layoutSource, /data-action="host-select-act"/);
  assert.match(layoutSource, /state\.hostSelectedActKey\s*\|\|\s*preferredActKey/);
  assert.match(layoutSource, /renderCurrentActColumn\(currentBeatKey, presentation\)/);
  assert.match(layoutSource, /data-action="host-tabletop-select-location"/);
  assert.match(layoutSource, /data-action="host-tabletop-toggle-map"/);
  assert.match(layoutSource, /data-action="host-tabletop-toggle-location"/);
  assert.match(layoutSource, /data-action="host-tabletop-start-check"/);
  assert.match(layoutSource, /data-action="host-tabletop-roll-check"/);
  assert.match(directorSource, /createRuntimeTabletopCheck/);
  assert.match(directorSource, /resolveRuntimeTabletopCheck/);
  for (const action of ["host-apply-remedy", "host-vote-status", "host-review-private-action", "host-review-testimony"]) {
    assert.match(layoutSource, new RegExp(`data-action=["']${action}["']`), `missing command center action: ${action}`);
  }
  assert.match(stylesSource, /host-command-center/);
  assert.match(stylesSource, /host-clue-grant-item/);
  assert.match(stylesSource, /host-task-item/);
  assert.match(stylesSource, /host-stage-map/);
  assert.match(stylesSource, /@media \(max-width: 1180px\)/);
});

test("landing view exposes room management for authenticated hosts", () => {
  const landingSource = readFileSync(path.join(root, "src", "views", "landing.js"), "utf8");
  const mainSource = readFileSync(path.join(root, "src", "main.js"), "utf8");
  const lifecycleSource = readFileSync(path.join(root, "src", "runtime", "host-lifecycle-controller.js"), "utf8");
  const roomControllerSource = readFileSync(path.join(root, "src", "runtime", "host-room-create-controller.js"), "utf8");
  const roomServiceSource = readFileSync(path.join(root, "src", "runtime", "host-room-create-service.js"), "utf8");
  assert.match(landingSource, /data-action="create-room"/);
  assert.match(landingSource, /data-action="refresh-rooms"/);
  assert.match(landingSource, /renderHostRoomCreateWorkspace/);
  assert.match(mainSource, /createHostRoomCreateController/);
  assert.match(roomControllerSource, /case "create-room"/);
  assert.match(roomControllerSource, /case "host-room-create-submit"/);
  assert.match(roomServiceSource, /idempotencyKey/);
  assert.doesNotMatch(`${mainSource}\n${lifecycleSource}\n${roomControllerSource}`, /window\.prompt|\bprompt\(/);
  assert.match(lifecycleSource, /case "refresh-rooms"/);
});

test("console render escapes user content", () => {
  const consoleSource = readFileSync(path.join(root, "src", "views", "console.js"), "utf8");
  const operationModelSource = readFileSync(path.join(root, "src", "runtime", "host-operation-model.js"), "utf8");
  const operationViewSource = readFileSync(path.join(root, "src", "views", "host-operation-workspace.js"), "utf8");
  const archiveViewSource = readFileSync(path.join(root, "src", "views", "host-archive-workspace.js"), "utf8");
  const ruleViewSource = readFileSync(path.join(root, "src", "views", "host-rule-workspace.js"), "utf8");
  const eventViewSource = readFileSync(path.join(root, "src", "views", "host-event-workspace.js"), "utf8");
  const voteViewSource = readFileSync(path.join(root, "src", "views", "host-vote-workspace.js"), "utf8");
  assert.match(consoleSource, /escapeHtml\(/);
  assert.match(operationModelSource, /hostActClueIds/);
  assert.match(operationModelSource, /resolveSectionSegmentKey/);
  assert.match(operationModelSource, /sectionOptionsForRole/);
  assert.match(operationModelSource, /selectedClueId/);
  assert.match(operationModelSource, /targetRoleIds/);
  assert.match(operationViewSource, /escapeHtml\(/);
  assert.match(archiveViewSource, /escapeHtml\(/);
  assert.match(ruleViewSource, /escapeHtml\(/);
  assert.match(eventViewSource, /escapeHtml\(/);
  assert.match(voteViewSource, /escapeHtml\(/);
  assert.doesNotMatch(`${operationModelSource}\n${operationViewSource}\n${archiveViewSource}\n${ruleViewSource}\n${eventViewSource}\n${voteViewSource}`, /modalEl|mountModal|modal-backdrop/);
});

test("host archive workspace owns recap and checkpoint transactions outside the invite modal", () => {
  const inviteSource = readFileSync(path.join(root, "src", "runtime", "invite.js"), "utf8");
  const controllerSource = readFileSync(path.join(root, "src", "runtime", "host-archive-controller.js"), "utf8");
  const serviceSource = readFileSync(path.join(root, "src", "runtime", "host-archive-service.js"), "utf8");
  const viewSource = readFileSync(path.join(root, "src", "views", "host-archive-workspace.js"), "utf8");
  assert.doesNotMatch(inviteSource, /openCreateRecapModal|openCreateCheckpointModal|studioField|studioValues/);
  assert.match(controllerSource, /createHostArchiveService/);
  assert.match(serviceSource, /idempotencyKey/);
  assert.match(serviceSource, /workspace\.roomId/);
  assert.match(viewSource, /data-host-archive-workspace/);
  assert.doesNotMatch(`${controllerSource}\n${serviceSource}\n${viewSource}`, /modalEl|mountModal|openModal|modal-backdrop/);
});

test("host rule workspace keeps permissions and list commands outside the editor transaction service", () => {
  const controllerSource = readFileSync(path.join(root, "src", "runtime", "host-rule-workspace-controller.js"), "utf8");
  const workspaceServiceSource = readFileSync(path.join(root, "src", "runtime", "host-rule-workspace-service.js"), "utf8");
  const listServiceSource = readFileSync(path.join(root, "src", "runtime", "host-rule-list-service.js"), "utf8");
  const permissionSource = readFileSync(path.join(root, "src", "runtime", "host-rule-permissions.js"), "utf8");
  assert.match(controllerSource, /createHostRuleListService/);
  assert.match(controllerSource, /createHostRuleWorkspaceService/);
  assert.match(workspaceServiceSource, /reconcileDelays/);
  assert.doesNotMatch(workspaceServiceSource, /async function (toggleRule|deleteRule|validateWorldRules)/);
  assert.match(listServiceSource, /async function toggleRule/);
  assert.match(listServiceSource, /async function deleteRule/);
  assert.match(permissionSource, /membership_role/);
  assert.match(permissionSource, /owner.*editor/);
  assert.doesNotMatch(`${controllerSource}\n${workspaceServiceSource}\n${listServiceSource}`, /modalEl|mountModal|openModal/);
});

test("standalone console keeps the full host monitoring action surface", () => {
  const consoleSource = readFileSync(path.join(root, "src", "views", "console.js"), "utf8");
  const layoutSource = readFileSync(path.join(root, "src", "views", "host-layout.js"), "utf8");
  const directorSource = readFileSync(path.join(root, "src", "runtime", "director-actions.js"), "utf8");
  const eventSource = readFileSync(path.join(root, "src", "runtime", "host-event-queue.js"), "utf8");
  const ruleSource = readFileSync(path.join(root, "src", "runtime", "host-rules-controller.js"), "utf8");
  const operationViewSource = readFileSync(path.join(root, "src", "views", "host-operation-workspace.js"), "utf8");
  const operationSource = readFileSync(path.join(root, "src", "runtime", "host-operation-controller.js"), "utf8");
  const archiveViewSource = readFileSync(path.join(root, "src", "views", "host-archive-workspace.js"), "utf8");
  const archiveSource = readFileSync(path.join(root, "src", "runtime", "host-archive-controller.js"), "utf8");
  const ruleViewSource = readFileSync(path.join(root, "src", "views", "host-rule-workspace.js"), "utf8");
  const ruleWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-rule-workspace-controller.js"), "utf8");
  const eventWorkspaceViewSource = readFileSync(path.join(root, "src", "views", "host-event-workspace.js"), "utf8");
  const eventWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-event-workspace-controller.js"), "utf8");
  const voteWorkspaceViewSource = readFileSync(path.join(root, "src", "views", "host-vote-workspace.js"), "utf8");
  const voteWorkspaceSource = readFileSync(path.join(root, "src", "runtime", "host-vote-workspace-controller.js"), "utf8");
  const hostSurface = `${consoleSource}\n${layoutSource}\n${eventSource}\n${ruleSource}\n${operationViewSource}\n${archiveViewSource}\n${ruleViewSource}\n${eventWorkspaceViewSource}\n${voteWorkspaceViewSource}`;
  const handlers = `${directorSource}\n${operationSource}\n${archiveSource}\n${ruleWorkspaceSource}\n${eventWorkspaceSource}\n${voteWorkspaceSource}`;
  const actions = [
    "batch-dismiss-host-events",
    "batch-execute-host-events",
    "copy-invite-code",
    "copy-play-link",
    "create-checkpoint",
    "create-recap",
    "delay-host-event",
    "dismiss-host-event",
    "execute-host-event",
    "host-clue-note",
    "host-create-vote",
    "host-event-context",
    "host-event-select-all",
    "host-event-toggle",
    "host-kick-player",
    "host-manual-grant-clue",
    "host-manual-grant-item",
    "host-manual-log",
    "host-manual-unlock-scene",
    "host-manual-unlock-section",
    "host-nudge-waiting",
    "host-stuck-intervene",
    "host-player-detail",
    "host-rule-delete-request",
    "host-rule-edit",
    "host-rule-new",
    "host-rule-toggle",
    "host-rule-validate",
    "onboarding-go-player",
    "refresh-host-audit",
    "refresh-host-clue-matrix",
    "refresh-host-events",
    "refresh-host-players",
    "refresh-host-room",
    "room-invite-current",
    "rule-manual-trigger",
    "rules-preview"
  ];

  for (const action of actions) {
    assert.match(hostSurface, new RegExp(`data-action=["']${action}["']`), `missing host action: ${action}`);
    assert.match(handlers, new RegExp(`["']${action}["']`), `missing action handler: ${action}`);
  }
});

test("host dev and preview share the documented port and API proxy", () => {
  const configSource = readFileSync(path.join(root, "vite.config.mjs"), "utf8");
  const packageSource = readFileSync(path.join(root, "package.json"), "utf8");
  assert.match(configSource, /VITE_HOST_DEV_PORT\s*\|\|\s*5175/);
  assert.match(configSource, /VITE_API_PROXY_TARGET\s*\|\|\s*"http:\/\/127\.0\.0\.1:4180"/);
  assert.match(configSource, /strictPort:\s*true/);
  assert.doesNotMatch(packageSource, /vite[^"\n]*--port/);
});

test("host shell exposes dedicated responsive workspace structure", () => {
  const shellSource = readFileSync(path.join(root, "src", "components", "shell.js"), "utf8");
  const headerSource = readFileSync(path.join(root, "src", "components", "header.js"), "utf8");
  const stylesSource = readFileSync(path.join(root, "src", "styles.css"), "utf8");
  assert.match(shellSource, /host-app-shell/);
  assert.match(headerSource, /host-header-inner/);
  assert.doesNotMatch(stylesSource, /\.host-console > \.director-head/);
  assert.match(stylesSource, /host-support-grid/);
  assert.match(stylesSource, /@media \(max-width: 520px\)/);
});
